import queue

fila = queue.Queue()
fila.put(12)
fila.put(34)
fila.put(99)
fila.put(82)
fila.put(10)
fila.put(22)
fila.put(76)
fila.put(100)
print('sua fila é ->', list(fila.queue))
print('sua fila tem', fila.qsize(), 'números')
print('a fila está vazia?', fila.empty())
print('a fila está cheia?', fila.full())
fila.put(73)
print(list(fila.queue))
fila.put_nowait(55)
print(list(fila.queue))
fila.get(99)
print(list(fila.queue))
fila.get_nowait()
print(list(fila.queue))
