nome = input('digite seu nome:')
nacionalidade = input('Qual é seu pais de origem:')
idade = input('Qual a sua idade:')
cidade = input('Em qual cidade você nasceu?')
cor_pref = input('Qual é a sua cor preferida?')

print('Nome: ' + nome)
print('Pais de origem: ' + nacionalidade)
print('Idade: ' + idade)
print('Cidade origem: ' + cidade)
print('Cor preferida: ' + cor_pref)